version: '3.4'

services:

 main.api:
  image: ${DOCKER_REGISTRY-}mainapi
  build:
   context: .
   dockerfile: Tweet-book/Dockerfile
  restart: always
  environment:
    - "ConnectionStrings:DefaultConnection=Server=db-server;Database=tweetdb;User Id=sa;Password=<admin@Passw0rd>"
  ports:
   - "7000:80"
  depends_on:
   - db-server

 db-server:
  image: mcr.microsoft.com/mssql/server
  container_name: db-server
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=<admin@Passw0rd>
  ports:
   - "1433:1433"
  volumes:
  - sql-volume:/var/opt/mssql

volumes:
 sql-volume: